// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: external_measurement_data.proto

#include "external_measurement_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_external_5fmeasurement_5fdata_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_external_5fmeasurement_5fdata_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto;
namespace tutorial {
class ExternalMeasurementDataBeanDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExternalMeasurementDataBean> _instance;
} _ExternalMeasurementDataBean_default_instance_;
class PredictDataBodyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PredictDataBody> _instance;
} _PredictDataBody_default_instance_;
class ParameterBodyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ParameterBody> _instance;
} _ParameterBody_default_instance_;
}  // namespace tutorial
static void InitDefaultsExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_ExternalMeasurementDataBean_default_instance_;
    new (ptr) ::tutorial::ExternalMeasurementDataBean();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::ExternalMeasurementDataBean::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto}, {
      &scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto.base,
      &scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto.base,}};

static void InitDefaultsPredictDataBody_external_5fmeasurement_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_PredictDataBody_default_instance_;
    new (ptr) ::tutorial::PredictDataBody();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::PredictDataBody::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPredictDataBody_external_5fmeasurement_5fdata_2eproto}, {}};

static void InitDefaultsParameterBody_external_5fmeasurement_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_ParameterBody_default_instance_;
    new (ptr) ::tutorial::ParameterBody();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::ParameterBody::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsParameterBody_external_5fmeasurement_5fdata_2eproto}, {}};

void InitDefaults_external_5fmeasurement_5fdata_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_external_5fmeasurement_5fdata_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_external_5fmeasurement_5fdata_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_external_5fmeasurement_5fdata_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_external_5fmeasurement_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tutorial::ExternalMeasurementDataBean, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tutorial::ExternalMeasurementDataBean, parameter_),
  PROTOBUF_FIELD_OFFSET(::tutorial::ExternalMeasurementDataBean, predictdata_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tutorial::PredictDataBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tutorial::PredictDataBody, datastr_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tutorial::ParameterBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tutorial::ParameterBody, spatialencoding_),
  PROTOBUF_FIELD_OFFSET(::tutorial::ParameterBody, begintime_),
  PROTOBUF_FIELD_OFFSET(::tutorial::ParameterBody, endtime_),
  PROTOBUF_FIELD_OFFSET(::tutorial::ParameterBody, devicename_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tutorial::ExternalMeasurementDataBean)},
  { 7, -1, sizeof(::tutorial::PredictDataBody)},
  { 13, -1, sizeof(::tutorial::ParameterBody)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tutorial::_ExternalMeasurementDataBean_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tutorial::_PredictDataBody_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tutorial::_ParameterBody_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_external_5fmeasurement_5fdata_2eproto = {
  {}, AddDescriptors_external_5fmeasurement_5fdata_2eproto, "external_measurement_data.proto", schemas,
  file_default_instances, TableStruct_external_5fmeasurement_5fdata_2eproto::offsets,
  file_level_metadata_external_5fmeasurement_5fdata_2eproto, 3, file_level_enum_descriptors_external_5fmeasurement_5fdata_2eproto, file_level_service_descriptors_external_5fmeasurement_5fdata_2eproto,
};

const char descriptor_table_protodef_external_5fmeasurement_5fdata_2eproto[] =
  "\n\037external_measurement_data.proto\022\010tutor"
  "ial\032\037google/protobuf/timestamp.proto\"y\n\033"
  "ExternalMeasurementDataBean\022*\n\tparameter"
  "\030\001 \001(\0132\027.tutorial.ParameterBody\022.\n\013predi"
  "ctData\030\002 \001(\0132\031.tutorial.PredictDataBody\""
  "\"\n\017PredictDataBody\022\017\n\007dataStr\030\001 \001(\t\"`\n\rP"
  "arameterBody\022\027\n\017spatialEncoding\030\001 \001(\t\022\021\n"
  "\tbeginTime\030\002 \001(\t\022\017\n\007endTime\030\003 \001(\t\022\022\n\ndev"
  "iceName\030\004 \001(\tB#\n\006com.xyB\031ExternalMeasure"
  "mentDataPbb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_external_5fmeasurement_5fdata_2eproto = {
  false, InitDefaults_external_5fmeasurement_5fdata_2eproto, 
  descriptor_table_protodef_external_5fmeasurement_5fdata_2eproto,
  "external_measurement_data.proto", &assign_descriptors_table_external_5fmeasurement_5fdata_2eproto, 378,
};

void AddDescriptors_external_5fmeasurement_5fdata_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2ftimestamp_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_external_5fmeasurement_5fdata_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_external_5fmeasurement_5fdata_2eproto = []() { AddDescriptors_external_5fmeasurement_5fdata_2eproto(); return true; }();
namespace tutorial {

// ===================================================================

void ExternalMeasurementDataBean::InitAsDefaultInstance() {
  ::tutorial::_ExternalMeasurementDataBean_default_instance_._instance.get_mutable()->parameter_ = const_cast< ::tutorial::ParameterBody*>(
      ::tutorial::ParameterBody::internal_default_instance());
  ::tutorial::_ExternalMeasurementDataBean_default_instance_._instance.get_mutable()->predictdata_ = const_cast< ::tutorial::PredictDataBody*>(
      ::tutorial::PredictDataBody::internal_default_instance());
}
class ExternalMeasurementDataBean::HasBitSetters {
 public:
  static const ::tutorial::ParameterBody& parameter(const ExternalMeasurementDataBean* msg);
  static const ::tutorial::PredictDataBody& predictdata(const ExternalMeasurementDataBean* msg);
};

const ::tutorial::ParameterBody&
ExternalMeasurementDataBean::HasBitSetters::parameter(const ExternalMeasurementDataBean* msg) {
  return *msg->parameter_;
}
const ::tutorial::PredictDataBody&
ExternalMeasurementDataBean::HasBitSetters::predictdata(const ExternalMeasurementDataBean* msg) {
  return *msg->predictdata_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExternalMeasurementDataBean::kParameterFieldNumber;
const int ExternalMeasurementDataBean::kPredictDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExternalMeasurementDataBean::ExternalMeasurementDataBean()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.ExternalMeasurementDataBean)
}
ExternalMeasurementDataBean::ExternalMeasurementDataBean(const ExternalMeasurementDataBean& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_parameter()) {
    parameter_ = new ::tutorial::ParameterBody(*from.parameter_);
  } else {
    parameter_ = nullptr;
  }
  if (from.has_predictdata()) {
    predictdata_ = new ::tutorial::PredictDataBody(*from.predictdata_);
  } else {
    predictdata_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tutorial.ExternalMeasurementDataBean)
}

void ExternalMeasurementDataBean::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto.base);
  ::memset(&parameter_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&predictdata_) -
      reinterpret_cast<char*>(&parameter_)) + sizeof(predictdata_));
}

ExternalMeasurementDataBean::~ExternalMeasurementDataBean() {
  // @@protoc_insertion_point(destructor:tutorial.ExternalMeasurementDataBean)
  SharedDtor();
}

void ExternalMeasurementDataBean::SharedDtor() {
  if (this != internal_default_instance()) delete parameter_;
  if (this != internal_default_instance()) delete predictdata_;
}

void ExternalMeasurementDataBean::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExternalMeasurementDataBean& ExternalMeasurementDataBean::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ExternalMeasurementDataBean_external_5fmeasurement_5fdata_2eproto.base);
  return *internal_default_instance();
}


void ExternalMeasurementDataBean::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.ExternalMeasurementDataBean)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && parameter_ != nullptr) {
    delete parameter_;
  }
  parameter_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && predictdata_ != nullptr) {
    delete predictdata_;
  }
  predictdata_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ExternalMeasurementDataBean::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ExternalMeasurementDataBean*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .tutorial.ParameterBody parameter = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tutorial::ParameterBody::_InternalParse;
        object = msg->mutable_parameter();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .tutorial.PredictDataBody predictData = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::tutorial::PredictDataBody::_InternalParse;
        object = msg->mutable_predictdata();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ExternalMeasurementDataBean::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.ExternalMeasurementDataBean)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tutorial.ParameterBody parameter = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_parameter()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tutorial.PredictDataBody predictData = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_predictdata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.ExternalMeasurementDataBean)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.ExternalMeasurementDataBean)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ExternalMeasurementDataBean::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.ExternalMeasurementDataBean)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tutorial.ParameterBody parameter = 1;
  if (this->has_parameter()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::parameter(this), output);
  }

  // .tutorial.PredictDataBody predictData = 2;
  if (this->has_predictdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::predictdata(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.ExternalMeasurementDataBean)
}

::google::protobuf::uint8* ExternalMeasurementDataBean::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.ExternalMeasurementDataBean)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tutorial.ParameterBody parameter = 1;
  if (this->has_parameter()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::parameter(this), target);
  }

  // .tutorial.PredictDataBody predictData = 2;
  if (this->has_predictdata()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::predictdata(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.ExternalMeasurementDataBean)
  return target;
}

size_t ExternalMeasurementDataBean::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.ExternalMeasurementDataBean)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tutorial.ParameterBody parameter = 1;
  if (this->has_parameter()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *parameter_);
  }

  // .tutorial.PredictDataBody predictData = 2;
  if (this->has_predictdata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *predictdata_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExternalMeasurementDataBean::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.ExternalMeasurementDataBean)
  GOOGLE_DCHECK_NE(&from, this);
  const ExternalMeasurementDataBean* source =
      ::google::protobuf::DynamicCastToGenerated<ExternalMeasurementDataBean>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.ExternalMeasurementDataBean)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.ExternalMeasurementDataBean)
    MergeFrom(*source);
  }
}

void ExternalMeasurementDataBean::MergeFrom(const ExternalMeasurementDataBean& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.ExternalMeasurementDataBean)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_parameter()) {
    mutable_parameter()->::tutorial::ParameterBody::MergeFrom(from.parameter());
  }
  if (from.has_predictdata()) {
    mutable_predictdata()->::tutorial::PredictDataBody::MergeFrom(from.predictdata());
  }
}

void ExternalMeasurementDataBean::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.ExternalMeasurementDataBean)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExternalMeasurementDataBean::CopyFrom(const ExternalMeasurementDataBean& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.ExternalMeasurementDataBean)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternalMeasurementDataBean::IsInitialized() const {
  return true;
}

void ExternalMeasurementDataBean::Swap(ExternalMeasurementDataBean* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExternalMeasurementDataBean::InternalSwap(ExternalMeasurementDataBean* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(parameter_, other->parameter_);
  swap(predictdata_, other->predictdata_);
}

::google::protobuf::Metadata ExternalMeasurementDataBean::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_external_5fmeasurement_5fdata_2eproto);
  return ::file_level_metadata_external_5fmeasurement_5fdata_2eproto[kIndexInFileMessages];
}


// ===================================================================

void PredictDataBody::InitAsDefaultInstance() {
}
class PredictDataBody::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PredictDataBody::kDataStrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PredictDataBody::PredictDataBody()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.PredictDataBody)
}
PredictDataBody::PredictDataBody(const PredictDataBody& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  datastr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.datastr().size() > 0) {
    datastr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.datastr_);
  }
  // @@protoc_insertion_point(copy_constructor:tutorial.PredictDataBody)
}

void PredictDataBody::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto.base);
  datastr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PredictDataBody::~PredictDataBody() {
  // @@protoc_insertion_point(destructor:tutorial.PredictDataBody)
  SharedDtor();
}

void PredictDataBody::SharedDtor() {
  datastr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PredictDataBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PredictDataBody& PredictDataBody::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_PredictDataBody_external_5fmeasurement_5fdata_2eproto.base);
  return *internal_default_instance();
}


void PredictDataBody::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.PredictDataBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  datastr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* PredictDataBody::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<PredictDataBody*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string dataStr = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("tutorial.PredictDataBody.dataStr");
        object = msg->mutable_datastr();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool PredictDataBody::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.PredictDataBody)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string dataStr = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_datastr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->datastr().data(), static_cast<int>(this->datastr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.PredictDataBody.dataStr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.PredictDataBody)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.PredictDataBody)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void PredictDataBody::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.PredictDataBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string dataStr = 1;
  if (this->datastr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->datastr().data(), static_cast<int>(this->datastr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.PredictDataBody.dataStr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->datastr(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.PredictDataBody)
}

::google::protobuf::uint8* PredictDataBody::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.PredictDataBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string dataStr = 1;
  if (this->datastr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->datastr().data(), static_cast<int>(this->datastr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.PredictDataBody.dataStr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->datastr(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.PredictDataBody)
  return target;
}

size_t PredictDataBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.PredictDataBody)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string dataStr = 1;
  if (this->datastr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->datastr());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PredictDataBody::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.PredictDataBody)
  GOOGLE_DCHECK_NE(&from, this);
  const PredictDataBody* source =
      ::google::protobuf::DynamicCastToGenerated<PredictDataBody>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.PredictDataBody)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.PredictDataBody)
    MergeFrom(*source);
  }
}

void PredictDataBody::MergeFrom(const PredictDataBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.PredictDataBody)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.datastr().size() > 0) {

    datastr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.datastr_);
  }
}

void PredictDataBody::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.PredictDataBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PredictDataBody::CopyFrom(const PredictDataBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.PredictDataBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PredictDataBody::IsInitialized() const {
  return true;
}

void PredictDataBody::Swap(PredictDataBody* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PredictDataBody::InternalSwap(PredictDataBody* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  datastr_.Swap(&other->datastr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata PredictDataBody::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_external_5fmeasurement_5fdata_2eproto);
  return ::file_level_metadata_external_5fmeasurement_5fdata_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ParameterBody::InitAsDefaultInstance() {
}
class ParameterBody::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParameterBody::kSpatialEncodingFieldNumber;
const int ParameterBody::kBeginTimeFieldNumber;
const int ParameterBody::kEndTimeFieldNumber;
const int ParameterBody::kDeviceNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParameterBody::ParameterBody()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.ParameterBody)
}
ParameterBody::ParameterBody(const ParameterBody& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  spatialencoding_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.spatialencoding().size() > 0) {
    spatialencoding_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.spatialencoding_);
  }
  begintime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.begintime().size() > 0) {
    begintime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.begintime_);
  }
  endtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.endtime().size() > 0) {
    endtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endtime_);
  }
  devicename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.devicename().size() > 0) {
    devicename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.devicename_);
  }
  // @@protoc_insertion_point(copy_constructor:tutorial.ParameterBody)
}

void ParameterBody::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto.base);
  spatialencoding_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  begintime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ParameterBody::~ParameterBody() {
  // @@protoc_insertion_point(destructor:tutorial.ParameterBody)
  SharedDtor();
}

void ParameterBody::SharedDtor() {
  spatialencoding_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  begintime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ParameterBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ParameterBody& ParameterBody::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ParameterBody_external_5fmeasurement_5fdata_2eproto.base);
  return *internal_default_instance();
}


void ParameterBody::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.ParameterBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  spatialencoding_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  begintime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ParameterBody::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ParameterBody*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string spatialEncoding = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("tutorial.ParameterBody.spatialEncoding");
        object = msg->mutable_spatialencoding();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string beginTime = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("tutorial.ParameterBody.beginTime");
        object = msg->mutable_begintime();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string endTime = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("tutorial.ParameterBody.endTime");
        object = msg->mutable_endtime();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string deviceName = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("tutorial.ParameterBody.deviceName");
        object = msg->mutable_devicename();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ParameterBody::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.ParameterBody)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string spatialEncoding = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_spatialencoding()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->spatialencoding().data(), static_cast<int>(this->spatialencoding().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.ParameterBody.spatialEncoding"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string beginTime = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_begintime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->begintime().data(), static_cast<int>(this->begintime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.ParameterBody.beginTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string endTime = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_endtime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->endtime().data(), static_cast<int>(this->endtime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.ParameterBody.endTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string deviceName = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_devicename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->devicename().data(), static_cast<int>(this->devicename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.ParameterBody.deviceName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.ParameterBody)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.ParameterBody)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ParameterBody::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.ParameterBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string spatialEncoding = 1;
  if (this->spatialencoding().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->spatialencoding().data(), static_cast<int>(this->spatialencoding().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.spatialEncoding");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->spatialencoding(), output);
  }

  // string beginTime = 2;
  if (this->begintime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->begintime().data(), static_cast<int>(this->begintime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.beginTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->begintime(), output);
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endtime().data(), static_cast<int>(this->endtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.endTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->endtime(), output);
  }

  // string deviceName = 4;
  if (this->devicename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicename().data(), static_cast<int>(this->devicename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.deviceName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->devicename(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.ParameterBody)
}

::google::protobuf::uint8* ParameterBody::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.ParameterBody)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string spatialEncoding = 1;
  if (this->spatialencoding().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->spatialencoding().data(), static_cast<int>(this->spatialencoding().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.spatialEncoding");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->spatialencoding(), target);
  }

  // string beginTime = 2;
  if (this->begintime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->begintime().data(), static_cast<int>(this->begintime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.beginTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->begintime(), target);
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endtime().data(), static_cast<int>(this->endtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.endTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->endtime(), target);
  }

  // string deviceName = 4;
  if (this->devicename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicename().data(), static_cast<int>(this->devicename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.ParameterBody.deviceName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->devicename(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.ParameterBody)
  return target;
}

size_t ParameterBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.ParameterBody)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string spatialEncoding = 1;
  if (this->spatialencoding().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->spatialencoding());
  }

  // string beginTime = 2;
  if (this->begintime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->begintime());
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->endtime());
  }

  // string deviceName = 4;
  if (this->devicename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->devicename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParameterBody::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.ParameterBody)
  GOOGLE_DCHECK_NE(&from, this);
  const ParameterBody* source =
      ::google::protobuf::DynamicCastToGenerated<ParameterBody>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.ParameterBody)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.ParameterBody)
    MergeFrom(*source);
  }
}

void ParameterBody::MergeFrom(const ParameterBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.ParameterBody)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.spatialencoding().size() > 0) {

    spatialencoding_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.spatialencoding_);
  }
  if (from.begintime().size() > 0) {

    begintime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.begintime_);
  }
  if (from.endtime().size() > 0) {

    endtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endtime_);
  }
  if (from.devicename().size() > 0) {

    devicename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.devicename_);
  }
}

void ParameterBody::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.ParameterBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParameterBody::CopyFrom(const ParameterBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.ParameterBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParameterBody::IsInitialized() const {
  return true;
}

void ParameterBody::Swap(ParameterBody* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParameterBody::InternalSwap(ParameterBody* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  spatialencoding_.Swap(&other->spatialencoding_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  begintime_.Swap(&other->begintime_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  endtime_.Swap(&other->endtime_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  devicename_.Swap(&other->devicename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata ParameterBody::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_external_5fmeasurement_5fdata_2eproto);
  return ::file_level_metadata_external_5fmeasurement_5fdata_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tutorial
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::tutorial::ExternalMeasurementDataBean* Arena::CreateMaybeMessage< ::tutorial::ExternalMeasurementDataBean >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::ExternalMeasurementDataBean >(arena);
}
template<> PROTOBUF_NOINLINE ::tutorial::PredictDataBody* Arena::CreateMaybeMessage< ::tutorial::PredictDataBody >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::PredictDataBody >(arena);
}
template<> PROTOBUF_NOINLINE ::tutorial::ParameterBody* Arena::CreateMaybeMessage< ::tutorial::ParameterBody >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::ParameterBody >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
